spring:
  cloud:
    config:
      name: data-import
    stream:
      bindings:
        output:
          destination: test
          contentType: text/plain
          #contentType: application/json
