server:
  port: 8761
spring:
  cloud:
    config:
      name: eureka-service

eureka:
  instance:
<<<<<<< Updated upstream
    #hostname: 192.168.99.100
    hostname: localhost
=======
   # hostname: 192.168.99.100
    hostname: 192.168.99.101
  #  hostname: localhost
>>>>>>> Stashed changes
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl :
      defaultZone: http://localhost:8761/eureka/
