server:
  port: 25000
spring:
  cloud:
    config:
      name: instrument-service
    stream:
      bindings:
        output:
          destination: instruments-saved
          #contentType: text/plain
          contentType: application/json
        input:
          destination: instruments-to-save
         # contentType: text/plain
          contentType: application/json
  data:
    neo4j:
      username: neo4j
      password: admin
      url: bolt://192.168.99.100:7687
