spring:
  cloud:
    config:
      name: instrument-service
    stream:
      bindings:
        output:
          destination: instruments
          #contentType: text/plain
          contentType: application/json
ribbon:
  DeploymentContextBasedVipAddresses: instrument-service
insrument-service:
  eureka:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList