spring:
  cloud:
    config:
      name: instrument-service
    stream:
      bindings:
        output:
          destination: candles
          #contentType: text/plain
          contentType: application/json
instrument-service:
  ribbon:
    listOfServers: http://192.168.99.100:80
