server:
  port: 8080
spring:
  cloud:
    config:
      name: zuul-service
zuul:
  routes:
    price-service: /prices/**
    instrument-service:
      path: /instruments/**
      url: http://docker/instruments/
    candle-service: /candles/**