server:
  port: 80
spring:
  cloud:
    config:
      name: zuul-service
zuul:
  routes:
    price-service: /prices/**
    instrument-service:
      path: /instruments/**
      serviceId: instrument-service
   candle-service: /candles/**