server:
  port: 80
spring:
  cloud:
    config:
      name: zuul-service
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
 routes:
    zuul-service:
      path: /self/**
      serviceId: zuul-service
    price-service:
      path: /prices/**
      serviceId: price-service
    instrument-service:
      path: /instruments/**
      serviceId: instrument-service
    candle-service:
      path: /candles/**
      serviceId: candle-service