server:
  port: 80
spring:
  cloud:
    config:
      name: zuul-service
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
 routes:
   zuul-service: /self/**
   price-service: /prices/**
   instrument-service: /instruments/**
   candle-service: /candles/**